// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: rpc/block.proto

package kot

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerifyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height    []byte `protobuf:"bytes,1,opt,name=Height,proto3" json:"Height,omitempty"`
	BlockHash []byte `protobuf:"bytes,2,opt,name=BlockHash,proto3" json:"BlockHash,omitempty"`
	Hash      []byte `protobuf:"bytes,3,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Time      []byte `protobuf:"bytes,4,opt,name=Time,proto3" json:"Time,omitempty"`
	Nonce     []byte `protobuf:"bytes,5,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
	Miner     []byte `protobuf:"bytes,6,opt,name=Miner,proto3" json:"Miner,omitempty"`
}

func (x *VerifyRequest) Reset() {
	*x = VerifyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_block_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRequest) ProtoMessage() {}

func (x *VerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_block_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRequest.ProtoReflect.Descriptor instead.
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return file_rpc_block_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyRequest) GetHeight() []byte {
	if x != nil {
		return x.Height
	}
	return nil
}

func (x *VerifyRequest) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *VerifyRequest) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *VerifyRequest) GetTime() []byte {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *VerifyRequest) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *VerifyRequest) GetMiner() []byte {
	if x != nil {
		return x.Miner
	}
	return nil
}

type TransactionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value   []byte `protobuf:"bytes,1,opt,name=Value,proto3" json:"Value,omitempty"`
	BaseFee []byte `protobuf:"bytes,2,opt,name=BaseFee,proto3" json:"BaseFee,omitempty"`
	To      []byte `protobuf:"bytes,3,opt,name=To,proto3" json:"To,omitempty"`
	Random  []byte `protobuf:"bytes,4,opt,name=Random,proto3" json:"Random,omitempty"`
	TxHash  []byte `protobuf:"bytes,5,opt,name=TxHash,proto3" json:"TxHash,omitempty"`
	Time    []byte `protobuf:"bytes,6,opt,name=Time,proto3" json:"Time,omitempty"`
	Nonce   []byte `protobuf:"bytes,7,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
	Sign    []byte `protobuf:"bytes,8,opt,name=Sign,proto3" json:"Sign,omitempty"`
}

func (x *TransactionRequest) Reset() {
	*x = TransactionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_block_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRequest) ProtoMessage() {}

func (x *TransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_block_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRequest.ProtoReflect.Descriptor instead.
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return file_rpc_block_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *TransactionRequest) GetBaseFee() []byte {
	if x != nil {
		return x.BaseFee
	}
	return nil
}

func (x *TransactionRequest) GetTo() []byte {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *TransactionRequest) GetRandom() []byte {
	if x != nil {
		return x.Random
	}
	return nil
}

func (x *TransactionRequest) GetTxHash() []byte {
	if x != nil {
		return x.TxHash
	}
	return nil
}

func (x *TransactionRequest) GetTime() []byte {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *TransactionRequest) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *TransactionRequest) GetSign() []byte {
	if x != nil {
		return x.Sign
	}
	return nil
}

type HashRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash []byte `protobuf:"bytes,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
}

func (x *HashRequest) Reset() {
	*x = HashRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_block_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashRequest) ProtoMessage() {}

func (x *HashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_block_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashRequest.ProtoReflect.Descriptor instead.
func (*HashRequest) Descriptor() ([]byte, []int) {
	return file_rpc_block_proto_rawDescGZIP(), []int{2}
}

func (x *HashRequest) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type AddressRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address []byte `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
}

func (x *AddressRequest) Reset() {
	*x = AddressRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_block_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressRequest) ProtoMessage() {}

func (x *AddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_block_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressRequest.ProtoReflect.Descriptor instead.
func (*AddressRequest) Descriptor() ([]byte, []int) {
	return file_rpc_block_proto_rawDescGZIP(), []int{3}
}

func (x *AddressRequest) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

type ReplyBool struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=Ok,proto3" json:"Ok,omitempty"`
}

func (x *ReplyBool) Reset() {
	*x = ReplyBool{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_block_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplyBool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyBool) ProtoMessage() {}

func (x *ReplyBool) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_block_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyBool.ProtoReflect.Descriptor instead.
func (*ReplyBool) Descriptor() ([]byte, []int) {
	return file_rpc_block_proto_rawDescGZIP(), []int{4}
}

func (x *ReplyBool) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ReplyValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	In  []byte `protobuf:"bytes,1,opt,name=In,proto3" json:"In,omitempty"`
	Out []byte `protobuf:"bytes,2,opt,name=Out,proto3" json:"Out,omitempty"`
}

func (x *ReplyValue) Reset() {
	*x = ReplyValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_block_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyValue) ProtoMessage() {}

func (x *ReplyValue) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_block_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyValue.ProtoReflect.Descriptor instead.
func (*ReplyValue) Descriptor() ([]byte, []int) {
	return file_rpc_block_proto_rawDescGZIP(), []int{5}
}

func (x *ReplyValue) GetIn() []byte {
	if x != nil {
		return x.In
	}
	return nil
}

func (x *ReplyValue) GetOut() []byte {
	if x != nil {
		return x.Out
	}
	return nil
}

type ReplyBalance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Balance []byte `protobuf:"bytes,1,opt,name=Balance,proto3" json:"Balance,omitempty"`
}

func (x *ReplyBalance) Reset() {
	*x = ReplyBalance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_block_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplyBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyBalance) ProtoMessage() {}

func (x *ReplyBalance) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_block_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyBalance.ProtoReflect.Descriptor instead.
func (*ReplyBalance) Descriptor() ([]byte, []int) {
	return file_rpc_block_proto_rawDescGZIP(), []int{6}
}

func (x *ReplyBalance) GetBalance() []byte {
	if x != nil {
		return x.Balance
	}
	return nil
}

type HeightRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height int64 `protobuf:"varint,1,opt,name=Height,proto3" json:"Height,omitempty"`
}

func (x *HeightRequest) Reset() {
	*x = HeightRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_block_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeightRequest) ProtoMessage() {}

func (x *HeightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_block_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeightRequest.ProtoReflect.Descriptor instead.
func (*HeightRequest) Descriptor() ([]byte, []int) {
	return file_rpc_block_proto_rawDescGZIP(), []int{7}
}

func (x *HeightRequest) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

type ReplyBlock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height      []byte              `protobuf:"bytes,1,opt,name=Height,proto3" json:"Height,omitempty"`
	Header      *Header             `protobuf:"bytes,2,opt,name=Header,proto3" json:"Header,omitempty"`
	Transaction []*ReplyTransaction `protobuf:"bytes,3,rep,name=Transaction,proto3" json:"Transaction,omitempty"`
}

func (x *ReplyBlock) Reset() {
	*x = ReplyBlock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_block_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplyBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyBlock) ProtoMessage() {}

func (x *ReplyBlock) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_block_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyBlock.ProtoReflect.Descriptor instead.
func (*ReplyBlock) Descriptor() ([]byte, []int) {
	return file_rpc_block_proto_rawDescGZIP(), []int{8}
}

func (x *ReplyBlock) GetHeight() []byte {
	if x != nil {
		return x.Height
	}
	return nil
}

func (x *ReplyBlock) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ReplyBlock) GetTransaction() []*ReplyTransaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type ReplyLatest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height []byte `protobuf:"bytes,1,opt,name=Height,proto3" json:"Height,omitempty"`
	Hash   []byte `protobuf:"bytes,2,opt,name=Hash,proto3" json:"Hash,omitempty"`
}

func (x *ReplyLatest) Reset() {
	*x = ReplyLatest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_block_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplyLatest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyLatest) ProtoMessage() {}

func (x *ReplyLatest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_block_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyLatest.ProtoReflect.Descriptor instead.
func (*ReplyLatest) Descriptor() ([]byte, []int) {
	return file_rpc_block_proto_rawDescGZIP(), []int{9}
}

func (x *ReplyLatest) GetHeight() []byte {
	if x != nil {
		return x.Height
	}
	return nil
}

func (x *ReplyLatest) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type Header struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ParentHash []byte `protobuf:"bytes,1,opt,name=ParentHash,proto3" json:"ParentHash,omitempty"`
	Hash       []byte `protobuf:"bytes,2,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Time       []byte `protobuf:"bytes,3,opt,name=Time,proto3" json:"Time,omitempty"`
	Nonce      []byte `protobuf:"bytes,4,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
	Miner      []byte `protobuf:"bytes,5,opt,name=Miner,proto3" json:"Miner,omitempty"`
}

func (x *Header) Reset() {
	*x = Header{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_block_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_block_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_rpc_block_proto_rawDescGZIP(), []int{10}
}

func (x *Header) GetParentHash() []byte {
	if x != nil {
		return x.ParentHash
	}
	return nil
}

func (x *Header) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *Header) GetTime() []byte {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Header) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *Header) GetMiner() []byte {
	if x != nil {
		return x.Miner
	}
	return nil
}

type ReplyTransaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value   []byte `protobuf:"bytes,1,opt,name=Value,proto3" json:"Value,omitempty"`
	BaseFee []byte `protobuf:"bytes,2,opt,name=BaseFee,proto3" json:"BaseFee,omitempty"`
	To      []byte `protobuf:"bytes,3,opt,name=To,proto3" json:"To,omitempty"`
	Random  []byte `protobuf:"bytes,4,opt,name=Random,proto3" json:"Random,omitempty"`
	TxHash  []byte `protobuf:"bytes,5,opt,name=TxHash,proto3" json:"TxHash,omitempty"`
	Time    []byte `protobuf:"bytes,6,opt,name=Time,proto3" json:"Time,omitempty"`
	Nonce   []byte `protobuf:"bytes,7,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
	Sign    []byte `protobuf:"bytes,8,opt,name=Sign,proto3" json:"Sign,omitempty"`
	State   bool   `protobuf:"varint,9,opt,name=State,proto3" json:"State,omitempty"`
}

func (x *ReplyTransaction) Reset() {
	*x = ReplyTransaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_block_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplyTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyTransaction) ProtoMessage() {}

func (x *ReplyTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_block_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyTransaction.ProtoReflect.Descriptor instead.
func (*ReplyTransaction) Descriptor() ([]byte, []int) {
	return file_rpc_block_proto_rawDescGZIP(), []int{11}
}

func (x *ReplyTransaction) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ReplyTransaction) GetBaseFee() []byte {
	if x != nil {
		return x.BaseFee
	}
	return nil
}

func (x *ReplyTransaction) GetTo() []byte {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *ReplyTransaction) GetRandom() []byte {
	if x != nil {
		return x.Random
	}
	return nil
}

func (x *ReplyTransaction) GetTxHash() []byte {
	if x != nil {
		return x.TxHash
	}
	return nil
}

func (x *ReplyTransaction) GetTime() []byte {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *ReplyTransaction) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *ReplyTransaction) GetSign() []byte {
	if x != nil {
		return x.Sign
	}
	return nil
}

func (x *ReplyTransaction) GetState() bool {
	if x != nil {
		return x.State
	}
	return false
}

type ReplyVerifys struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Verifys []*ReplyVerify `protobuf:"bytes,1,rep,name=Verifys,proto3" json:"Verifys,omitempty"`
}

func (x *ReplyVerifys) Reset() {
	*x = ReplyVerifys{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_block_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplyVerifys) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyVerifys) ProtoMessage() {}

func (x *ReplyVerifys) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_block_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyVerifys.ProtoReflect.Descriptor instead.
func (*ReplyVerifys) Descriptor() ([]byte, []int) {
	return file_rpc_block_proto_rawDescGZIP(), []int{12}
}

func (x *ReplyVerifys) GetVerifys() []*ReplyVerify {
	if x != nil {
		return x.Verifys
	}
	return nil
}

type ReplyVerify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height    []byte `protobuf:"bytes,1,opt,name=Height,proto3" json:"Height,omitempty"`
	BlockHash []byte `protobuf:"bytes,2,opt,name=BlockHash,proto3" json:"BlockHash,omitempty"`
	Hash      []byte `protobuf:"bytes,3,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Time      []byte `protobuf:"bytes,4,opt,name=Time,proto3" json:"Time,omitempty"`
	Nonce     []byte `protobuf:"bytes,5,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
	Miner     []byte `protobuf:"bytes,6,opt,name=Miner,proto3" json:"Miner,omitempty"`
}

func (x *ReplyVerify) Reset() {
	*x = ReplyVerify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_block_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplyVerify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyVerify) ProtoMessage() {}

func (x *ReplyVerify) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_block_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyVerify.ProtoReflect.Descriptor instead.
func (*ReplyVerify) Descriptor() ([]byte, []int) {
	return file_rpc_block_proto_rawDescGZIP(), []int{13}
}

func (x *ReplyVerify) GetHeight() []byte {
	if x != nil {
		return x.Height
	}
	return nil
}

func (x *ReplyVerify) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *ReplyVerify) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *ReplyVerify) GetTime() []byte {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *ReplyVerify) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *ReplyVerify) GetMiner() []byte {
	if x != nil {
		return x.Miner
	}
	return nil
}

var File_rpc_block_proto protoreflect.FileDescriptor

var file_rpc_block_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x72, 0x70, 0x63, 0x2f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0c, 0x4b, 0x6f, 0x74, 0x46, 0x6c, 0x6f, 0x77, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x22,
	0x99, 0x01, 0x0a, 0x0d, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x06, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x61, 0x73, 0x68, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x48, 0x61, 0x73, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x54,
	0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05,
	0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x69, 0x6e, 0x65, 0x72, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x4d, 0x69, 0x6e, 0x65, 0x72, 0x22, 0xc2, 0x01, 0x0a, 0x12,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x42, 0x61, 0x73, 0x65,
	0x46, 0x65, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x42, 0x61, 0x73, 0x65, 0x46,
	0x65, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x54, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02,
	0x54, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x06, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x78,
	0x48, 0x61, 0x73, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x54, 0x78, 0x48, 0x61,
	0x73, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x53, 0x69, 0x67, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x53, 0x69, 0x67, 0x6e,
	0x22, 0x21, 0x0a, 0x0b, 0x48, 0x61, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x48, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x48,
	0x61, 0x73, 0x68, 0x22, 0x2a, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22,
	0x1b, 0x0a, 0x09, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x6f, 0x6f, 0x6c, 0x12, 0x0e, 0x0a, 0x02,
	0x4f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x4f, 0x6b, 0x22, 0x2e, 0x0a, 0x0a,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x49, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x4f, 0x75,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x4f, 0x75, 0x74, 0x22, 0x28, 0x0a, 0x0c,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x42,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x22, 0x27, 0x0a, 0x0d, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x48, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22,
	0x94, 0x01, 0x0a, 0x0a, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x16,
	0x0a, 0x06, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06,
	0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x2c, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x4b, 0x6f, 0x74, 0x46, 0x6c, 0x6f, 0x77,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x12, 0x40, 0x0a, 0x0b, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x4b, 0x6f, 0x74, 0x46,
	0x6c, 0x6f, 0x77, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x39, 0x0a, 0x0b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x4c,
	0x61, 0x74, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x48, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x48, 0x61, 0x73,
	0x68, 0x22, 0x7c, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x50,
	0x61, 0x72, 0x65, 0x6e, 0x74, 0x48, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0a, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x48, 0x61, 0x73, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x48,
	0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x48, 0x61, 0x73, 0x68, 0x12,
	0x12, 0x0a, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x05, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x69, 0x6e,
	0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x4d, 0x69, 0x6e, 0x65, 0x72, 0x22,
	0xd6, 0x01, 0x0a, 0x10, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x42, 0x61,
	0x73, 0x65, 0x46, 0x65, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x42, 0x61, 0x73,
	0x65, 0x46, 0x65, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x54, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x02, 0x54, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x12, 0x16, 0x0a, 0x06,
	0x54, 0x78, 0x48, 0x61, 0x73, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x54, 0x78,
	0x48, 0x61, 0x73, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x4e, 0x6f, 0x6e, 0x63,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x53, 0x69, 0x67, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x53, 0x69,
	0x67, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0x43, 0x0a, 0x0c, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x73, 0x12, 0x33, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x69,
	0x66, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x4b, 0x6f, 0x74, 0x46,
	0x6c, 0x6f, 0x77, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x79, 0x52, 0x07, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x73, 0x22, 0x97, 0x01,
	0x0a, 0x0b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x12, 0x16, 0x0a,
	0x06, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x48,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61,
	0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48,
	0x61, 0x73, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x48, 0x61, 0x73, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x4e,
	0x6f, 0x6e, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x4e, 0x6f, 0x6e, 0x63,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x69, 0x6e, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x05, 0x4d, 0x69, 0x6e, 0x65, 0x72, 0x32, 0xf5, 0x05, 0x0a, 0x07, 0x47, 0x72, 0x65, 0x65,
	0x74, 0x65, 0x72, 0x12, 0x49, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x1b, 0x2e, 0x4b, 0x6f, 0x74, 0x46, 0x6c, 0x6f, 0x77, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x18, 0x2e, 0x4b, 0x6f, 0x74, 0x46, 0x6c, 0x6f, 0x77, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x00, 0x12, 0x45,
	0x0a, 0x09, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x2e, 0x4b, 0x6f,
	0x74, 0x46, 0x6c, 0x6f, 0x77, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x48, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x4b, 0x6f, 0x74, 0x46, 0x6c,
	0x6f, 0x77, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x4c, 0x61, 0x74,
	0x65, 0x73, 0x74, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x42, 0x72, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x19, 0x2e, 0x4b, 0x6f, 0x74, 0x46, 0x6c, 0x6f, 0x77, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e,
	0x4b, 0x6f, 0x74, 0x46, 0x6c, 0x6f, 0x77, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x42, 0x6f, 0x6f, 0x6c, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1c, 0x2e, 0x4b, 0x6f,
	0x74, 0x46, 0x6c, 0x6f, 0x77, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x4b, 0x6f, 0x74, 0x46,
	0x6c, 0x6f, 0x77, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0x00, 0x12, 0x4f, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x1c, 0x2e, 0x4b, 0x6f, 0x74,
	0x46, 0x6c, 0x6f, 0x77, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x4b, 0x6f, 0x74, 0x46, 0x6c,
	0x6f, 0x77, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x61, 0x6c,
	0x61, 0x6e, 0x63, 0x65, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x2e, 0x4b, 0x6f, 0x74, 0x46, 0x6c,
	0x6f, 0x77, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x4b, 0x6f, 0x74, 0x46, 0x6c, 0x6f, 0x77, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x09, 0x50, 0x75, 0x74, 0x56, 0x65, 0x72, 0x69,
	0x66, 0x79, 0x12, 0x1b, 0x2e, 0x4b, 0x6f, 0x74, 0x46, 0x6c, 0x6f, 0x77, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x17, 0x2e, 0x4b, 0x6f, 0x74, 0x46, 0x6c, 0x6f, 0x77, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x42, 0x6f, 0x6f, 0x6c, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x0e, 0x50, 0x75,
	0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x2e, 0x4b,
	0x6f, 0x74, 0x46, 0x6c, 0x6f, 0x77, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17,
	0x2e, 0x4b, 0x6f, 0x74, 0x46, 0x6c, 0x6f, 0x77, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x42, 0x6f, 0x6f, 0x6c, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x0f, 0x47, 0x65, 0x74,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x1b, 0x2e, 0x4b,
	0x6f, 0x74, 0x46, 0x6c, 0x6f, 0x77, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x48, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x4b, 0x6f, 0x74, 0x46,
	0x6c, 0x6f, 0x77, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x79, 0x73, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0e, 0x48, 0x61, 0x73, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x2e, 0x4b, 0x6f, 0x74, 0x46,
	0x6c, 0x6f, 0x77, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x4b, 0x6f, 0x74, 0x46, 0x6c, 0x6f, 0x77, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x6f, 0x6f, 0x6c, 0x22, 0x00, 0x42,
	0x0c, 0x5a, 0x0a, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2f, 0x6b, 0x6f, 0x74, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_block_proto_rawDescOnce sync.Once
	file_rpc_block_proto_rawDescData = file_rpc_block_proto_rawDesc
)

func file_rpc_block_proto_rawDescGZIP() []byte {
	file_rpc_block_proto_rawDescOnce.Do(func() {
		file_rpc_block_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_block_proto_rawDescData)
	})
	return file_rpc_block_proto_rawDescData
}

var file_rpc_block_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_rpc_block_proto_goTypes = []interface{}{
	(*VerifyRequest)(nil),      // 0: KotFlowBlock.VerifyRequest
	(*TransactionRequest)(nil), // 1: KotFlowBlock.TransactionRequest
	(*HashRequest)(nil),        // 2: KotFlowBlock.HashRequest
	(*AddressRequest)(nil),     // 3: KotFlowBlock.AddressRequest
	(*ReplyBool)(nil),          // 4: KotFlowBlock.ReplyBool
	(*ReplyValue)(nil),         // 5: KotFlowBlock.ReplyValue
	(*ReplyBalance)(nil),       // 6: KotFlowBlock.ReplyBalance
	(*HeightRequest)(nil),      // 7: KotFlowBlock.HeightRequest
	(*ReplyBlock)(nil),         // 8: KotFlowBlock.ReplyBlock
	(*ReplyLatest)(nil),        // 9: KotFlowBlock.ReplyLatest
	(*Header)(nil),             // 10: KotFlowBlock.Header
	(*ReplyTransaction)(nil),   // 11: KotFlowBlock.ReplyTransaction
	(*ReplyVerifys)(nil),       // 12: KotFlowBlock.ReplyVerifys
	(*ReplyVerify)(nil),        // 13: KotFlowBlock.ReplyVerify
}
var file_rpc_block_proto_depIdxs = []int32{
	10, // 0: KotFlowBlock.ReplyBlock.Header:type_name -> KotFlowBlock.Header
	11, // 1: KotFlowBlock.ReplyBlock.Transaction:type_name -> KotFlowBlock.ReplyTransaction
	13, // 2: KotFlowBlock.ReplyVerifys.Verifys:type_name -> KotFlowBlock.ReplyVerify
	7,  // 3: KotFlowBlock.Greeter.GetBlockHeight:input_type -> KotFlowBlock.HeightRequest
	7,  // 4: KotFlowBlock.Greeter.GetLatest:input_type -> KotFlowBlock.HeightRequest
	2,  // 5: KotFlowBlock.Greeter.GetBroken:input_type -> KotFlowBlock.HashRequest
	3,  // 6: KotFlowBlock.Greeter.GetAddressValue:input_type -> KotFlowBlock.AddressRequest
	3,  // 7: KotFlowBlock.Greeter.GetAddressBalance:input_type -> KotFlowBlock.AddressRequest
	2,  // 8: KotFlowBlock.Greeter.GetTransaction:input_type -> KotFlowBlock.HashRequest
	0,  // 9: KotFlowBlock.Greeter.PutVerify:input_type -> KotFlowBlock.VerifyRequest
	1,  // 10: KotFlowBlock.Greeter.PutTransaction:input_type -> KotFlowBlock.TransactionRequest
	7,  // 11: KotFlowBlock.Greeter.GetVerifyHeight:input_type -> KotFlowBlock.HeightRequest
	2,  // 12: KotFlowBlock.Greeter.HasTransaction:input_type -> KotFlowBlock.HashRequest
	8,  // 13: KotFlowBlock.Greeter.GetBlockHeight:output_type -> KotFlowBlock.ReplyBlock
	9,  // 14: KotFlowBlock.Greeter.GetLatest:output_type -> KotFlowBlock.ReplyLatest
	4,  // 15: KotFlowBlock.Greeter.GetBroken:output_type -> KotFlowBlock.ReplyBool
	5,  // 16: KotFlowBlock.Greeter.GetAddressValue:output_type -> KotFlowBlock.ReplyValue
	6,  // 17: KotFlowBlock.Greeter.GetAddressBalance:output_type -> KotFlowBlock.ReplyBalance
	11, // 18: KotFlowBlock.Greeter.GetTransaction:output_type -> KotFlowBlock.ReplyTransaction
	4,  // 19: KotFlowBlock.Greeter.PutVerify:output_type -> KotFlowBlock.ReplyBool
	4,  // 20: KotFlowBlock.Greeter.PutTransaction:output_type -> KotFlowBlock.ReplyBool
	12, // 21: KotFlowBlock.Greeter.GetVerifyHeight:output_type -> KotFlowBlock.ReplyVerifys
	4,  // 22: KotFlowBlock.Greeter.HasTransaction:output_type -> KotFlowBlock.ReplyBool
	13, // [13:23] is the sub-list for method output_type
	3,  // [3:13] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_rpc_block_proto_init() }
func file_rpc_block_proto_init() {
	if File_rpc_block_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_block_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_block_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransactionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_block_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HashRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_block_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddressRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_block_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplyBool); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_block_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplyValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_block_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplyBalance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_block_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeightRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_block_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplyBlock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_block_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplyLatest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_block_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Header); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_block_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplyTransaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_block_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplyVerifys); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_block_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplyVerify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_block_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_block_proto_goTypes,
		DependencyIndexes: file_rpc_block_proto_depIdxs,
		MessageInfos:      file_rpc_block_proto_msgTypes,
	}.Build()
	File_rpc_block_proto = out.File
	file_rpc_block_proto_rawDesc = nil
	file_rpc_block_proto_goTypes = nil
	file_rpc_block_proto_depIdxs = nil
}
