# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/block.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("rpc/block.proto", :syntax => :proto3) do
    add_message "KotFlowBlock.HeightRequest" do
      optional :Height, :int64, 1
    end
    add_message "KotFlowBlock.Block" do
      optional :Height, :bytes, 1
      optional :Header, :message, 2, "KotFlowBlock.Header"
      repeated :Transaction, :message, 3, "KotFlowBlock.Transaction"
    end
    add_message "KotFlowBlock.Header" do
      optional :ParentHash, :bytes, 1
      optional :Hash, :bytes, 2
      optional :Time, :bytes, 3
      optional :Nonce, :bytes, 4
      optional :Miner, :bytes, 5
    end
    add_message "KotFlowBlock.Transaction" do
      optional :Value, :bytes, 1
      optional :BaseFee, :bytes, 2
      optional :To, :bytes, 3
      optional :Random, :bytes, 4
      optional :TxHash, :bytes, 5
      optional :Time, :bytes, 6
      optional :Nonce, :bytes, 7
      optional :Sign, :bytes, 8
      optional :State, :bool, 9
    end
  end
end

module KotFlowBlock
  HeightRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("KotFlowBlock.HeightRequest").msgclass
  Block = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("KotFlowBlock.Block").msgclass
  Header = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("KotFlowBlock.Header").msgclass
  Transaction = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("KotFlowBlock.Transaction").msgclass
end
