# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/block.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0frpc/block.proto\x12\x0cKotFlowBlock\"\x1f\n\rHeightRequest\x12\x0e\n\x06Height\x18\x01 \x01(\x03\"m\n\x05\x42lock\x12\x0e\n\x06Height\x18\x01 \x01(\x0c\x12$\n\x06Header\x18\x02 \x01(\x0b\x32\x14.KotFlowBlock.Header\x12.\n\x0bTransaction\x18\x03 \x03(\x0b\x32\x19.KotFlowBlock.Transaction\"V\n\x06Header\x12\x12\n\nParentHash\x18\x01 \x01(\x0c\x12\x0c\n\x04Hash\x18\x02 \x01(\x0c\x12\x0c\n\x04Time\x18\x03 \x01(\x0c\x12\r\n\x05Nonce\x18\x04 \x01(\x0c\x12\r\n\x05Miner\x18\x05 \x01(\x0c\"\x93\x01\n\x0bTransaction\x12\r\n\x05Value\x18\x01 \x01(\x0c\x12\x0f\n\x07\x42\x61seFee\x18\x02 \x01(\x0c\x12\n\n\x02To\x18\x03 \x01(\x0c\x12\x0e\n\x06Random\x18\x04 \x01(\x0c\x12\x0e\n\x06TxHash\x18\x05 \x01(\x0c\x12\x0c\n\x04Time\x18\x06 \x01(\x0c\x12\r\n\x05Nonce\x18\x07 \x01(\x0c\x12\x0c\n\x04Sign\x18\x08 \x01(\x0c\x12\r\n\x05State\x18\t \x01(\x08\x32L\n\x07Greeter\x12\x41\n\x0b\x42lockHeight\x12\x1b.KotFlowBlock.HeightRequest\x1a\x13.KotFlowBlock.Block\"\x00\x42\x0cZ\ngolang/kotb\x06proto3')



_HEIGHTREQUEST = DESCRIPTOR.message_types_by_name['HeightRequest']
_BLOCK = DESCRIPTOR.message_types_by_name['Block']
_HEADER = DESCRIPTOR.message_types_by_name['Header']
_TRANSACTION = DESCRIPTOR.message_types_by_name['Transaction']
HeightRequest = _reflection.GeneratedProtocolMessageType('HeightRequest', (_message.Message,), {
  'DESCRIPTOR' : _HEIGHTREQUEST,
  '__module__' : 'rpc.block_pb2'
  # @@protoc_insertion_point(class_scope:KotFlowBlock.HeightRequest)
  })
_sym_db.RegisterMessage(HeightRequest)

Block = _reflection.GeneratedProtocolMessageType('Block', (_message.Message,), {
  'DESCRIPTOR' : _BLOCK,
  '__module__' : 'rpc.block_pb2'
  # @@protoc_insertion_point(class_scope:KotFlowBlock.Block)
  })
_sym_db.RegisterMessage(Block)

Header = _reflection.GeneratedProtocolMessageType('Header', (_message.Message,), {
  'DESCRIPTOR' : _HEADER,
  '__module__' : 'rpc.block_pb2'
  # @@protoc_insertion_point(class_scope:KotFlowBlock.Header)
  })
_sym_db.RegisterMessage(Header)

Transaction = _reflection.GeneratedProtocolMessageType('Transaction', (_message.Message,), {
  'DESCRIPTOR' : _TRANSACTION,
  '__module__' : 'rpc.block_pb2'
  # @@protoc_insertion_point(class_scope:KotFlowBlock.Transaction)
  })
_sym_db.RegisterMessage(Transaction)

_GREETER = DESCRIPTOR.services_by_name['Greeter']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\ngolang/kot'
  _HEIGHTREQUEST._serialized_start=33
  _HEIGHTREQUEST._serialized_end=64
  _BLOCK._serialized_start=66
  _BLOCK._serialized_end=175
  _HEADER._serialized_start=177
  _HEADER._serialized_end=263
  _TRANSACTION._serialized_start=266
  _TRANSACTION._serialized_end=413
  _GREETER._serialized_start=415
  _GREETER._serialized_end=491
# @@protoc_insertion_point(module_scope)
