// source: rpc/block.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.KotFlowBlock.ReplyBlock');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.KotFlowBlock.Header');
goog.require('proto.KotFlowBlock.ReplyTransaction');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.KotFlowBlock.ReplyBlock = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.KotFlowBlock.ReplyBlock.repeatedFields_, null);
};
goog.inherits(proto.KotFlowBlock.ReplyBlock, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.KotFlowBlock.ReplyBlock.displayName = 'proto.KotFlowBlock.ReplyBlock';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.KotFlowBlock.ReplyBlock.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.KotFlowBlock.ReplyBlock.prototype.toObject = function(opt_includeInstance) {
  return proto.KotFlowBlock.ReplyBlock.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.KotFlowBlock.ReplyBlock} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.KotFlowBlock.ReplyBlock.toObject = function(includeInstance, msg) {
  var f, obj = {
    height: msg.getHeight_asB64(),
    header: (f = msg.getHeader()) && proto.KotFlowBlock.Header.toObject(includeInstance, f),
    transactionList: jspb.Message.toObjectList(msg.getTransactionList(),
    proto.KotFlowBlock.ReplyTransaction.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.KotFlowBlock.ReplyBlock}
 */
proto.KotFlowBlock.ReplyBlock.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.KotFlowBlock.ReplyBlock;
  return proto.KotFlowBlock.ReplyBlock.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.KotFlowBlock.ReplyBlock} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.KotFlowBlock.ReplyBlock}
 */
proto.KotFlowBlock.ReplyBlock.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setHeight(value);
      break;
    case 2:
      var value = new proto.KotFlowBlock.Header;
      reader.readMessage(value,proto.KotFlowBlock.Header.deserializeBinaryFromReader);
      msg.setHeader(value);
      break;
    case 3:
      var value = new proto.KotFlowBlock.ReplyTransaction;
      reader.readMessage(value,proto.KotFlowBlock.ReplyTransaction.deserializeBinaryFromReader);
      msg.addTransaction(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.KotFlowBlock.ReplyBlock.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.KotFlowBlock.ReplyBlock.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.KotFlowBlock.ReplyBlock} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.KotFlowBlock.ReplyBlock.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHeight_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = message.getHeader();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.KotFlowBlock.Header.serializeBinaryToWriter
    );
  }
  f = message.getTransactionList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.KotFlowBlock.ReplyTransaction.serializeBinaryToWriter
    );
  }
};


/**
 * optional bytes Height = 1;
 * @return {string}
 */
proto.KotFlowBlock.ReplyBlock.prototype.getHeight = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes Height = 1;
 * This is a type-conversion wrapper around `getHeight()`
 * @return {string}
 */
proto.KotFlowBlock.ReplyBlock.prototype.getHeight_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getHeight()));
};


/**
 * optional bytes Height = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getHeight()`
 * @return {!Uint8Array}
 */
proto.KotFlowBlock.ReplyBlock.prototype.getHeight_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getHeight()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.KotFlowBlock.ReplyBlock} returns this
 */
proto.KotFlowBlock.ReplyBlock.prototype.setHeight = function(value) {
  return jspb.Message.setProto3BytesField(this, 1, value);
};


/**
 * optional Header Header = 2;
 * @return {?proto.KotFlowBlock.Header}
 */
proto.KotFlowBlock.ReplyBlock.prototype.getHeader = function() {
  return /** @type{?proto.KotFlowBlock.Header} */ (
    jspb.Message.getWrapperField(this, proto.KotFlowBlock.Header, 2));
};


/**
 * @param {?proto.KotFlowBlock.Header|undefined} value
 * @return {!proto.KotFlowBlock.ReplyBlock} returns this
*/
proto.KotFlowBlock.ReplyBlock.prototype.setHeader = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.KotFlowBlock.ReplyBlock} returns this
 */
proto.KotFlowBlock.ReplyBlock.prototype.clearHeader = function() {
  return this.setHeader(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.KotFlowBlock.ReplyBlock.prototype.hasHeader = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated ReplyTransaction Transaction = 3;
 * @return {!Array<!proto.KotFlowBlock.ReplyTransaction>}
 */
proto.KotFlowBlock.ReplyBlock.prototype.getTransactionList = function() {
  return /** @type{!Array<!proto.KotFlowBlock.ReplyTransaction>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.KotFlowBlock.ReplyTransaction, 3));
};


/**
 * @param {!Array<!proto.KotFlowBlock.ReplyTransaction>} value
 * @return {!proto.KotFlowBlock.ReplyBlock} returns this
*/
proto.KotFlowBlock.ReplyBlock.prototype.setTransactionList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.KotFlowBlock.ReplyTransaction=} opt_value
 * @param {number=} opt_index
 * @return {!proto.KotFlowBlock.ReplyTransaction}
 */
proto.KotFlowBlock.ReplyBlock.prototype.addTransaction = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.KotFlowBlock.ReplyTransaction, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.KotFlowBlock.ReplyBlock} returns this
 */
proto.KotFlowBlock.ReplyBlock.prototype.clearTransactionList = function() {
  return this.setTransactionList([]);
};


