// source: rpc/block.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.KotFlowBlock.VerifyRequest');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.KotFlowBlock.VerifyRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.KotFlowBlock.VerifyRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.KotFlowBlock.VerifyRequest.displayName = 'proto.KotFlowBlock.VerifyRequest';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.KotFlowBlock.VerifyRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.KotFlowBlock.VerifyRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.KotFlowBlock.VerifyRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.KotFlowBlock.VerifyRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    height: msg.getHeight_asB64(),
    blockhash: msg.getBlockhash_asB64(),
    hash: msg.getHash_asB64(),
    time: msg.getTime_asB64(),
    nonce: msg.getNonce_asB64(),
    miner: msg.getMiner_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.KotFlowBlock.VerifyRequest}
 */
proto.KotFlowBlock.VerifyRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.KotFlowBlock.VerifyRequest;
  return proto.KotFlowBlock.VerifyRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.KotFlowBlock.VerifyRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.KotFlowBlock.VerifyRequest}
 */
proto.KotFlowBlock.VerifyRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setHeight(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setBlockhash(value);
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setHash(value);
      break;
    case 4:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setTime(value);
      break;
    case 5:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setNonce(value);
      break;
    case 6:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setMiner(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.KotFlowBlock.VerifyRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.KotFlowBlock.VerifyRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.KotFlowBlock.VerifyRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.KotFlowBlock.VerifyRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHeight_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = message.getBlockhash_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      2,
      f
    );
  }
  f = message.getHash_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      3,
      f
    );
  }
  f = message.getTime_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      4,
      f
    );
  }
  f = message.getNonce_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      5,
      f
    );
  }
  f = message.getMiner_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      6,
      f
    );
  }
};


/**
 * optional bytes Height = 1;
 * @return {string}
 */
proto.KotFlowBlock.VerifyRequest.prototype.getHeight = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes Height = 1;
 * This is a type-conversion wrapper around `getHeight()`
 * @return {string}
 */
proto.KotFlowBlock.VerifyRequest.prototype.getHeight_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getHeight()));
};


/**
 * optional bytes Height = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getHeight()`
 * @return {!Uint8Array}
 */
proto.KotFlowBlock.VerifyRequest.prototype.getHeight_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getHeight()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.KotFlowBlock.VerifyRequest} returns this
 */
proto.KotFlowBlock.VerifyRequest.prototype.setHeight = function(value) {
  return jspb.Message.setProto3BytesField(this, 1, value);
};


/**
 * optional bytes BlockHash = 2;
 * @return {string}
 */
proto.KotFlowBlock.VerifyRequest.prototype.getBlockhash = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes BlockHash = 2;
 * This is a type-conversion wrapper around `getBlockhash()`
 * @return {string}
 */
proto.KotFlowBlock.VerifyRequest.prototype.getBlockhash_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getBlockhash()));
};


/**
 * optional bytes BlockHash = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getBlockhash()`
 * @return {!Uint8Array}
 */
proto.KotFlowBlock.VerifyRequest.prototype.getBlockhash_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getBlockhash()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.KotFlowBlock.VerifyRequest} returns this
 */
proto.KotFlowBlock.VerifyRequest.prototype.setBlockhash = function(value) {
  return jspb.Message.setProto3BytesField(this, 2, value);
};


/**
 * optional bytes Hash = 3;
 * @return {string}
 */
proto.KotFlowBlock.VerifyRequest.prototype.getHash = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * optional bytes Hash = 3;
 * This is a type-conversion wrapper around `getHash()`
 * @return {string}
 */
proto.KotFlowBlock.VerifyRequest.prototype.getHash_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getHash()));
};


/**
 * optional bytes Hash = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getHash()`
 * @return {!Uint8Array}
 */
proto.KotFlowBlock.VerifyRequest.prototype.getHash_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getHash()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.KotFlowBlock.VerifyRequest} returns this
 */
proto.KotFlowBlock.VerifyRequest.prototype.setHash = function(value) {
  return jspb.Message.setProto3BytesField(this, 3, value);
};


/**
 * optional bytes Time = 4;
 * @return {string}
 */
proto.KotFlowBlock.VerifyRequest.prototype.getTime = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * optional bytes Time = 4;
 * This is a type-conversion wrapper around `getTime()`
 * @return {string}
 */
proto.KotFlowBlock.VerifyRequest.prototype.getTime_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getTime()));
};


/**
 * optional bytes Time = 4;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getTime()`
 * @return {!Uint8Array}
 */
proto.KotFlowBlock.VerifyRequest.prototype.getTime_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getTime()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.KotFlowBlock.VerifyRequest} returns this
 */
proto.KotFlowBlock.VerifyRequest.prototype.setTime = function(value) {
  return jspb.Message.setProto3BytesField(this, 4, value);
};


/**
 * optional bytes Nonce = 5;
 * @return {string}
 */
proto.KotFlowBlock.VerifyRequest.prototype.getNonce = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * optional bytes Nonce = 5;
 * This is a type-conversion wrapper around `getNonce()`
 * @return {string}
 */
proto.KotFlowBlock.VerifyRequest.prototype.getNonce_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getNonce()));
};


/**
 * optional bytes Nonce = 5;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getNonce()`
 * @return {!Uint8Array}
 */
proto.KotFlowBlock.VerifyRequest.prototype.getNonce_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getNonce()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.KotFlowBlock.VerifyRequest} returns this
 */
proto.KotFlowBlock.VerifyRequest.prototype.setNonce = function(value) {
  return jspb.Message.setProto3BytesField(this, 5, value);
};


/**
 * optional bytes Miner = 6;
 * @return {string}
 */
proto.KotFlowBlock.VerifyRequest.prototype.getMiner = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * optional bytes Miner = 6;
 * This is a type-conversion wrapper around `getMiner()`
 * @return {string}
 */
proto.KotFlowBlock.VerifyRequest.prototype.getMiner_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getMiner()));
};


/**
 * optional bytes Miner = 6;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getMiner()`
 * @return {!Uint8Array}
 */
proto.KotFlowBlock.VerifyRequest.prototype.getMiner_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getMiner()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.KotFlowBlock.VerifyRequest} returns this
 */
proto.KotFlowBlock.VerifyRequest.prototype.setMiner = function(value) {
  return jspb.Message.setProto3BytesField(this, 6, value);
};


