<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/block.proto

namespace KotFlowBlock;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>KotFlowBlock.AddressRequest</code>
 */
class AddressRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes Address = 1;</code>
     */
    protected $Address = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Address
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc\Block::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes Address = 1;</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->Address;
    }

    /**
     * Generated from protobuf field <code>bytes Address = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, False);
        $this->Address = $var;

        return $this;
    }

}

