<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/block.proto

namespace KotFlowBlock;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>KotFlowBlock.ReplyValue</code>
 */
class ReplyValue extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes In = 1;</code>
     */
    protected $In = '';
    /**
     * Generated from protobuf field <code>bytes Out = 2;</code>
     */
    protected $Out = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $In
     *     @type string $Out
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc\Block::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes In = 1;</code>
     * @return string
     */
    public function getIn()
    {
        return $this->In;
    }

    /**
     * Generated from protobuf field <code>bytes In = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setIn($var)
    {
        GPBUtil::checkString($var, False);
        $this->In = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes Out = 2;</code>
     * @return string
     */
    public function getOut()
    {
        return $this->Out;
    }

    /**
     * Generated from protobuf field <code>bytes Out = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setOut($var)
    {
        GPBUtil::checkString($var, False);
        $this->Out = $var;

        return $this;
    }

}

