<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/block.proto

namespace KotFlowBlock;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>KotFlowBlock.ReplyBalance</code>
 */
class ReplyBalance extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes Balance = 1;</code>
     */
    protected $Balance = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Balance
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc\Block::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes Balance = 1;</code>
     * @return string
     */
    public function getBalance()
    {
        return $this->Balance;
    }

    /**
     * Generated from protobuf field <code>bytes Balance = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBalance($var)
    {
        GPBUtil::checkString($var, False);
        $this->Balance = $var;

        return $this;
    }

}

