<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/block.proto

namespace KotFlowBlock;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>KotFlowBlock.ReplyBool</code>
 */
class ReplyBool extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool Ok = 1;</code>
     */
    protected $Ok = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $Ok
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc\Block::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool Ok = 1;</code>
     * @return bool
     */
    public function getOk()
    {
        return $this->Ok;
    }

    /**
     * Generated from protobuf field <code>bool Ok = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setOk($var)
    {
        GPBUtil::checkBool($var);
        $this->Ok = $var;

        return $this;
    }

}

