<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/block.proto

namespace KotFlowBlock;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>KotFlowBlock.ReplyVerifys</code>
 */
class ReplyVerifys extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .KotFlowBlock.ReplyVerify Verifys = 1;</code>
     */
    private $Verifys;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \KotFlowBlock\ReplyVerify[]|\Google\Protobuf\Internal\RepeatedField $Verifys
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc\Block::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .KotFlowBlock.ReplyVerify Verifys = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getVerifys()
    {
        return $this->Verifys;
    }

    /**
     * Generated from protobuf field <code>repeated .KotFlowBlock.ReplyVerify Verifys = 1;</code>
     * @param \KotFlowBlock\ReplyVerify[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setVerifys($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \KotFlowBlock\ReplyVerify::class);
        $this->Verifys = $arr;

        return $this;
    }

}

