<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/block.proto

namespace KotFlowBlock;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>KotFlowBlock.ReplyBlock</code>
 */
class ReplyBlock extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes Height = 1;</code>
     */
    protected $Height = '';
    /**
     * Generated from protobuf field <code>.KotFlowBlock.Header Header = 2;</code>
     */
    protected $Header = null;
    /**
     * Generated from protobuf field <code>repeated .KotFlowBlock.ReplyTransaction Transaction = 3;</code>
     */
    private $Transaction;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Height
     *     @type \KotFlowBlock\Header $Header
     *     @type \KotFlowBlock\ReplyTransaction[]|\Google\Protobuf\Internal\RepeatedField $Transaction
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc\Block::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes Height = 1;</code>
     * @return string
     */
    public function getHeight()
    {
        return $this->Height;
    }

    /**
     * Generated from protobuf field <code>bytes Height = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setHeight($var)
    {
        GPBUtil::checkString($var, False);
        $this->Height = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.KotFlowBlock.Header Header = 2;</code>
     * @return \KotFlowBlock\Header|null
     */
    public function getHeader()
    {
        return $this->Header;
    }

    public function hasHeader()
    {
        return isset($this->Header);
    }

    public function clearHeader()
    {
        unset($this->Header);
    }

    /**
     * Generated from protobuf field <code>.KotFlowBlock.Header Header = 2;</code>
     * @param \KotFlowBlock\Header $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \KotFlowBlock\Header::class);
        $this->Header = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .KotFlowBlock.ReplyTransaction Transaction = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTransaction()
    {
        return $this->Transaction;
    }

    /**
     * Generated from protobuf field <code>repeated .KotFlowBlock.ReplyTransaction Transaction = 3;</code>
     * @param \KotFlowBlock\ReplyTransaction[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTransaction($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \KotFlowBlock\ReplyTransaction::class);
        $this->Transaction = $arr;

        return $this;
    }

}

