<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/block.proto

namespace KotFlowBlock;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>KotFlowBlock.ReplyVerify</code>
 */
class ReplyVerify extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes Height = 1;</code>
     */
    protected $Height = '';
    /**
     * Generated from protobuf field <code>bytes BlockHash = 2;</code>
     */
    protected $BlockHash = '';
    /**
     * Generated from protobuf field <code>bytes Hash = 3;</code>
     */
    protected $Hash = '';
    /**
     * Generated from protobuf field <code>bytes Time = 4;</code>
     */
    protected $Time = '';
    /**
     * Generated from protobuf field <code>bytes Nonce = 5;</code>
     */
    protected $Nonce = '';
    /**
     * Generated from protobuf field <code>bytes Miner = 6;</code>
     */
    protected $Miner = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Height
     *     @type string $BlockHash
     *     @type string $Hash
     *     @type string $Time
     *     @type string $Nonce
     *     @type string $Miner
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc\Block::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes Height = 1;</code>
     * @return string
     */
    public function getHeight()
    {
        return $this->Height;
    }

    /**
     * Generated from protobuf field <code>bytes Height = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setHeight($var)
    {
        GPBUtil::checkString($var, False);
        $this->Height = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes BlockHash = 2;</code>
     * @return string
     */
    public function getBlockHash()
    {
        return $this->BlockHash;
    }

    /**
     * Generated from protobuf field <code>bytes BlockHash = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setBlockHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->BlockHash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes Hash = 3;</code>
     * @return string
     */
    public function getHash()
    {
        return $this->Hash;
    }

    /**
     * Generated from protobuf field <code>bytes Hash = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->Hash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes Time = 4;</code>
     * @return string
     */
    public function getTime()
    {
        return $this->Time;
    }

    /**
     * Generated from protobuf field <code>bytes Time = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setTime($var)
    {
        GPBUtil::checkString($var, False);
        $this->Time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes Nonce = 5;</code>
     * @return string
     */
    public function getNonce()
    {
        return $this->Nonce;
    }

    /**
     * Generated from protobuf field <code>bytes Nonce = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setNonce($var)
    {
        GPBUtil::checkString($var, False);
        $this->Nonce = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes Miner = 6;</code>
     * @return string
     */
    public function getMiner()
    {
        return $this->Miner;
    }

    /**
     * Generated from protobuf field <code>bytes Miner = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setMiner($var)
    {
        GPBUtil::checkString($var, False);
        $this->Miner = $var;

        return $this;
    }

}

