<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/block.proto

namespace KotFlowBlock;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>KotFlowBlock.TransactionRequest</code>
 */
class TransactionRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes Value = 1;</code>
     */
    protected $Value = '';
    /**
     * Generated from protobuf field <code>bytes BaseFee = 2;</code>
     */
    protected $BaseFee = '';
    /**
     * Generated from protobuf field <code>bytes To = 3;</code>
     */
    protected $To = '';
    /**
     * Generated from protobuf field <code>bytes Random = 4;</code>
     */
    protected $Random = '';
    /**
     * Generated from protobuf field <code>bytes TxHash = 5;</code>
     */
    protected $TxHash = '';
    /**
     * Generated from protobuf field <code>bytes Time = 6;</code>
     */
    protected $Time = '';
    /**
     * Generated from protobuf field <code>bytes Nonce = 7;</code>
     */
    protected $Nonce = '';
    /**
     * Generated from protobuf field <code>bytes Sign = 8;</code>
     */
    protected $Sign = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Value
     *     @type string $BaseFee
     *     @type string $To
     *     @type string $Random
     *     @type string $TxHash
     *     @type string $Time
     *     @type string $Nonce
     *     @type string $Sign
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc\Block::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes Value = 1;</code>
     * @return string
     */
    public function getValue()
    {
        return $this->Value;
    }

    /**
     * Generated from protobuf field <code>bytes Value = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, False);
        $this->Value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes BaseFee = 2;</code>
     * @return string
     */
    public function getBaseFee()
    {
        return $this->BaseFee;
    }

    /**
     * Generated from protobuf field <code>bytes BaseFee = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setBaseFee($var)
    {
        GPBUtil::checkString($var, False);
        $this->BaseFee = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes To = 3;</code>
     * @return string
     */
    public function getTo()
    {
        return $this->To;
    }

    /**
     * Generated from protobuf field <code>bytes To = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTo($var)
    {
        GPBUtil::checkString($var, False);
        $this->To = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes Random = 4;</code>
     * @return string
     */
    public function getRandom()
    {
        return $this->Random;
    }

    /**
     * Generated from protobuf field <code>bytes Random = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setRandom($var)
    {
        GPBUtil::checkString($var, False);
        $this->Random = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes TxHash = 5;</code>
     * @return string
     */
    public function getTxHash()
    {
        return $this->TxHash;
    }

    /**
     * Generated from protobuf field <code>bytes TxHash = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setTxHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->TxHash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes Time = 6;</code>
     * @return string
     */
    public function getTime()
    {
        return $this->Time;
    }

    /**
     * Generated from protobuf field <code>bytes Time = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setTime($var)
    {
        GPBUtil::checkString($var, False);
        $this->Time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes Nonce = 7;</code>
     * @return string
     */
    public function getNonce()
    {
        return $this->Nonce;
    }

    /**
     * Generated from protobuf field <code>bytes Nonce = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setNonce($var)
    {
        GPBUtil::checkString($var, False);
        $this->Nonce = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes Sign = 8;</code>
     * @return string
     */
    public function getSign()
    {
        return $this->Sign;
    }

    /**
     * Generated from protobuf field <code>bytes Sign = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setSign($var)
    {
        GPBUtil::checkString($var, False);
        $this->Sign = $var;

        return $this;
    }

}

